schema: ${GRAPHQL_ENDPOINT}
documents:
    - 'src/**/*.{ts,tsx}'
    - '!src/graphql/*'
generates:
    src/graphql/index.tsx:
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - fragment-matcher
        config:
            nonOptionalTypename: true
            scalars:
                Upload: File
            withComponent: false
            withHOC: false
            withHooks: true
